version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: 362695547081.dkr.ecr.us-east-1.amazonaws.com/repo-1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION::7}
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPOSITORY:$IMAGE_TAG
      - echo Creating imagedefinitions.json for ECS deployment...
      - printf '[{"name":"repo-1","imageUri":"%s"}]' $ECR_REPOSITORY:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
